services:
  - type: web
    name: elemes
    env: python
    rootDir: ELMS1.3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
